### ISSUE TITLE
Avoid multiple `Vertex` definitions on `.proto` files

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/ts-topology#150]
We currently have double `Vertex` definitions on the network proto file and objects file. The network file is supposed to import the object one. Were having problems setting this because of the monorepo structure. `buf` is crying about something

**Comment by KevinMB0220** [comment]
Hi Kevin, to resolve the issue with the duplicated `Vertex` definition, I would first remove the duplicate definition from the `network.proto` file and instead import the `objects.proto` file where `Vertex` is already defined. Then, I would ensure that the `network.proto` file properly references the imported `Vertex` definition. After that, I’d verify that the import paths are correctly set in the `buf.yaml` or `buf.gen.yaml` configuration, aligned with the monorepo structure. Finally, I would run `buf lint` or `buf generate` to ensure that all duplications and path issues are resolved. This should address the complaints from `buf`.

**Comment by KevinMB0220** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/topology).

### My background and how it can be leveraged
Hello @d-roak, to resolve the issue with the duplicated Vertex definition, I would first remove the duplicate definition from the network.proto file and instead import the objects.proto file where Vertex is already defined. Then, I would ensure that the network.proto file properly references the imported Vertex definition. After that, I’d verify that the import paths are correctly set in the buf.yaml or buf.gen.yaml configuration, aligned with the monorepo structure. Finally, I would run buf lint or buf generate to ensure that all duplications and path issues are resolved. This should address the complaints from buf.

**Comment by d-roak** [comment]
Assigned! If you have any questions, feel free to join our community channels:

https://t.me/topologyfrens
https://discord.gg/GUDGzBP5mn

**Comment by d-roak** [comment]
more than 1 week of inactivity, i'm going to take the assignment

**Comment by supreme2580** [comment]
@d-roak Can I be assigned to this?

**Comment by d-roak** [comment]
sure

**Comment by supreme2580** [comment]
@d-roak hey boss, turns out i'm travelling and won't be available to handle this, thank you for the opportunity🙏🏽

**Comment by sfroment** [comment]
Hey @d-roak ,
I have a solution for that but right now when you run proto-gen on main it will make a dir in `packages/src/proto` is that intended ?

**Comment by d-roak** [comment]
completed in #205
