### ISSUE TITLE
Use `Vertex` from protobuf everywhere

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/ts-topology#151]
Currently in the HashGraph we have a `Vertex` interface, should be replaced with the protobuf definition

**Comment by CristopherAguilar10** [comment]
Hello @d-roak Can I work on this issue? I would like to help, I have knowledge in full stack and I would like to contribute. Thanks for the opportunity

**Comment by d-roak** [comment]
Assigned! If you have any questions, feel free to join our community channels:

https://t.me/topologyfrens
https://discord.gg/GUDGzBP5mn

**Comment by d-roak** [comment]
Taking the assignment. No updates for more than 1 week and other person interested

**Comment by cwkang1998** [comment]
Would be great if I can attempt this!
