### ISSUE TITLE
Add benchmarking to ci pipeline

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/ts-topology#154]
We did some testing on #153 to add benchmarking on our CI with `vitest bench`. 
Didn't liked the results, we want to have a well-formatted benchmarking system to compare with pull-requests and between commits on main.

The goal is to benchmark:
- code performance
- memory consumption
- CPU benchmarking

We want to use:
- https://benchmarkjs.com/ (optional)
- https://github.com/benchmark-action/github-action-benchmark (required)

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/topology).

### My background and how it can be leveraged
Hi D-Roak,

I am a frontend developer with over a year of experience in React, JavaScript, and TypeScript. Throughout my career, I've built production-ready applications, and recently, I've developed a strong interest in blockchain technology. I’ve already contributed to Starknet React by creating a new useWatchAssets hook and improving the documentation.

I’m confident that my determination and willingness to learn will enable me to deliver on this task, and I’m excited to take on this challenge.

Looking forward to hearing from you!



### How I plan on tackling this issue
Clone the project on my pc
Spin it up following the documentation
Review the existing codebase to understand how the code works
make research on how the problem
Implement the researched solution and test

**Comment by d-roak** [comment]
Hey, @deeseeker. We are open to all contributions, we'll review whatever PR you come up with. If you have any questions, feel free to join our community channels:
- https://t.me/topologyfrens
- https://discord.gg/GUDGzBP5mn

**Comment by deeseeker** [comment]
Thanks.
I will join the group to update you on my progress.

**Comment by d-roak** [comment]
Unassigning after @deeseeker confirmation in dm

**Comment by Solomonsolomonsolomon** [comment]
@d-roak  can I take a look at this

**Comment by d-roak** [comment]
yes, assigned

**Comment by d-roak** [comment]
unassigned due to inactivity
