### ISSUE TITLE
Bug with invalid dependencies in the hash graph

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/ts-topology#160]
There's a bug in the Hash Graph when sending updates in the network related with invalid dependencies. Needs further investigation.

Reproduction:
- Run one example
- Do some actions
- Run a second instance of the example and connect to the same CRO id
- Do some actions with the first instance (it should appear on the second)
- Do some actions with the second instance (it will show errors on the console of the first instance with invalid dependencies)

**Comment by chachaleo** [comment]
Can I work on this ? :)

**Comment by d-roak** [comment]
ohh sorry, it was urgent in our pipeline so i went ahead. Feel free to pick other issues !
