### ISSUE TITLE
Bad dependencies if peers discover each other after both connecting to the same CRO

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#185]
Bad dependencies cause the vertices sent by one peer to be rejected by another peer. 

https://github.com/user-attachments/assets/ae3bd8e7-d69e-4af9-8ad6-3acc51e96a35

**Comment by d-roak** [comment]
not fixed
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/3a1b74d3-0fde-4c2b-aec8-71ebad1418a0">

**Comment by elielnfinic** [comment]
noted

**Comment by d-roak** [comment]
fixed
