### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/ts-topology#67]
Currently we are using `console.log` and `console.err` for debugging. We want to create a debug mode where we can check logs, otherwise they shouldn't be displayed.

Research and implement the best approach you can find for this

**Comment by JanLewDev** [comment]
I'm on it.

**Comment by d-roak** [comment]
done at #102 , needs further investigation on how to:
- properly log nested objects without showing too much info
- implement generic logging for types that throw errors

**Comment by gregemax** [comment]
i will like to work on it 

Tell us about your background and how it can be leveraged:
I have a strong background in TypeScript, specializing in creating efficient logging utilities. My experience will help implement a robust solution that enhances maintainability and debugging in our projects.


How would you approach the problem?
Define Debug Mode: Use an environment variable to toggle debug mode.

Create a Logger: Develop a TypeScript logger that wraps console.log and checks debug mode.

Integrate the Logger: Replace existing logging calls for consistency.

Testing: Ensure logs behave as expected in both modes.

**Comment by d-roak** [comment]
Go ahead! Assigned

**Comment by d-roak** [comment]
Any further attempts, please check previous PRs for extra comments. One extra thing that was not mentioned in the last round of comments:
- We want to be able to setup different log levels and configs to each package. The log configs should be passed in the constructor of each package

**Comment by d-roak** [comment]
for tracking #172

**Comment by gregemax** [comment]
hey 
consider a logger like winston or pino with browser-specific handling plugins for more control over object logging and nested data.

**Comment by d-roak** [comment]
hey @gregemax, are you going to continue this task or can i drop the assignment and close the pr?

**Comment by gregemax** [comment]
@d-roak 
should i use  winston or pino  for the logger

**Comment by d-roak** [comment]
winston

**Comment by d-roak** [comment]
assigning it internally
