### ISSUE TITLE
Implement built-in CRDTs: infinite-phase set

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#80]
### Background
We already have 2PSet. Infinite-phase set is a generalization of it, allowing elements to be removed and re-added ad infinitum. This should be useful as a built-in CRDT for constructing CROs.

The idea is pretty simple. Use a GCounter to represent the presence of an element. The counter value being odd means the element is present. The counter value being even means the element is not present.

### Task
- implement it
- test it
- document how this type works and its usage

### Resources
- Original paper: https://arxiv.org/abs/2304.01929
- Reference prototype in Go: https://github.com/guiltygyoza/go-crdt/blob/master/infphase_set.go

**Comment by JanLewDev** [comment]
I'm starting to work on the implementation
