### ISSUE TITLE
Implement built-in CRDTs: LSEQ (array type)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#82]
### Background
CRDT has its origin in the collaborative document use case. The document is modeled as an array of characters that can be concurrently edited (character insertion & deletion). There are lots of array/sequence CRDTs for this purpose. The two basic ones are LSEQ and RGA. This issue tracks LSEQ implementation and testing.

### Task
- implement 
- test
- document how this type works and its usage

### Resources
- https://hal.science/hal-00921633/document original paper
- https://www.bartoszsypytkowski.com/operation-based-crdts-arrays-1/
- https://docs.rs/crdts/latest/crdts/list/index.html the Rust crate for CRDT also implements their array type as LSEQ

**Comment by joaopereira12** [comment]
I got it.

**Comment by d-roak** [comment]
not using crdt builtins anymore
