### ISSUE TITLE
Implement built-in CRDTs: RGA (array type)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#83]
### Description
Same as the description of #82. This issue tracks the implementation and testing of RGA.

### Task
- implement
- test
- document how this type works and its usage

### Resources
- https://www.sciencedirect.com/science/article/abs/pii/S0743731510002716 original paper
- https://github.com/Horusiath/crdt-examples/blob/master/Crdt/commutative/Rga.fs Bartosz's implementation
- https://josephg.com/blog/crdts-go-brrr/ this seminal blogpost in the CRDT circle also covers how RGA works

**Comment by JanLewDev** [comment]
I'm on it.
