### ISSUE TITLE
Implement built-in CRDTs: YATA (array type)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#84]
### Background
YATA is another array type, which is popularized by [Yjs](https://yjs.dev/). Yjs is a popular CRDT library, which we used to make Penguin World.

### Task
- implement
- test
- document how this type works and its usage

### Resources
- https://www.researchgate.net/publication/310212186_Near_Real-Time_Peer-to-Peer_Shared_Editing_on_Extensible_Data_Types original paper; PDF available: https://files.gitter.im/y-js/yjs/yCYx/GROUP2016-_6_.pdf
- https://www.bartoszsypytkowski.com/yata/ Bartosz's explanation

**Comment by d-roak** [comment]
not using crdt builtins anymore
