### ISSUE TITLE
Implement built-in CRDTs: Fugue (advanced array type)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#85]
### Description
Fugue is a famous array type CRDT designed to solve the interleaving problem that plagues most other array types.

### Task
- implement
- test
- document how this type works and its usage

### Resources
- https://arxiv.org/abs/2305.00583 the original paper
- https://mattweidner.com/2022/10/21/basic-list-crdt.html Fugue explained by its author Matthew Weidner

**Comment by d-roak** [comment]
not using crdt builtins anymore
