### ISSUE TITLE
Implement built-in CRDTs: JSON (complex nested type)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#86]
### Description
JSON is a very expressive format. Having JSON-CRDT as a built-in allows CRO to represent more complex data.

Note: supporting undo/redo and supporting moving subtrees around as a group can be tricky (because there can be concurrent edits to elements in the subtree).

### Task
- implement
- test
- document how this type works and its usage

### Resources
- https://members.loria.fr/CIgnat/files/replication/CRDT-JSON.pdf the original paper
- https://github.com/automerge/automerge implementation by Automerge, a popular CRDT library
- https://arxiv.org/abs/2311.14007 follow-up paper extending JSON-CRDT with richer operations
- https://arxiv.org/abs/2404.11308 this may be helpful for understanding how undo/redo can be done

**Comment by d-roak** [comment]
not using crdt builtins anymore
