### ISSUE TITLE
Documentation: explain how existing built-in types work

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#87]
We already have 2PSet, GCounter, GSet, LWWElementSet, and PNCounter implemented under `packages/crdt`. Document how they work and their usage in separate READMEs.

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/topology).

### My background and how it can be leveraged
I'm a software developer with 2+ years of experience with Java, C#, Dart and others technologies and I'm member of Dojo Coding community here in CR. I would like to contribute to this project.

### How I plan on tackling this issue
I would improve the current documentation by providing a clear explanation of each built-in CRDT type, including its core functionality and typical use cases. Additionally, I would ensure the structure is accessible for both newcomers and experienced developers, focusing on simplicity while covering essential details.

**Comment by d-roak** [comment]
Hi @coxmars this issue is not available. Thank you so much for reaching out! Feel free to pick up on other issues

**Comment by coxmars** [comment]
> Hi @coxmars this issue is not available. Thank you so much for reaching out! Feel free to pick up on other issues

Thank you for letting me know, I will apply to other issues, thank you 🫡
