### ISSUE TITLE
Implement built-in CRDTs: grow-only map (GMap)

### ISSUE THREAD

**Issue by guiltygyoza** [topology-foundation/ts-topology#92]
### Background
Map types are useful. Grow-only map (GMap) is a add-only map where keys can be anything and values are CRDTs (meaning GMap can be used to build nested types).

### Task
- implement
- test
- document how this type works and its usage

### Resources
- https://github.com/CBaquero/delta-enabled-crdts

**Comment by d-roak** [comment]
not using crdt builtins anymore
